name: renty_crud_version
description: Renty application with built in CRUD features.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_chips_input: ^1.7.0
  cloud_functions: ^0.4.2+2
  flutter_picker: ^1.1.0
  supercharged: ^1.2.1
  jiffy: ^3.0.1
  persistent_bottom_nav_bar: ^1.2.0
  photo_view: ^0.9.1
  expandable: ^4.1.2
  flutter_form_builder: ^3.8.0+1
  permission_handler: "^4.2.0+hotfix.3"
  cached_network_image: ^2.0.0
  firebase_messaging: ^6.0.9
  logger: ^0.6.0
  flutter_datetime_picker: ^1.3.5

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  # http request
  http: ^0.12.0+4
  # async package to add additional Cancellable operations
  async: ^2.0.8
  # get it
  get_it: ^3.0.0+1
  # provider
  provider: ^3.2.0
  # provider architecture
  provider_architecture: ^1.0.3
  #firebase stuffs
  cloud_firestore: ^0.13.0+1
  firebase_auth: ^0.15.4
  firebase_core: ^0.4.3+3
  firebase_storage: ^3.1.1
  multi_image_picker: ^4.6.1
  flutter_staggered_grid_view: ^0.3.0
  flutter_typeahead: ^1.8.0
  shimmer: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/logo.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Open Sans
      fonts:
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/OpenSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 300
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 400
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
