const String OnboardingPageRoute = "OnboardingPage";
const String LoginViewRoute = "LoginView";
const String SignUpViewRoute = "SignUp";
const String HomeViewRoute = "HomeView";
const String ItemDetailViewRoute = "ItemDetailView";
const String ItemLendViewRoute = "ItemLendView";
const String ItemTransactionViewRoute = "ItemTransactionView";
const String HomeTabViewRoute = "HomeTabView";
const String MyProfilePageRoute = "MyProfilePage";
const String MyItemsPageRoute = "MyItemsPage";
const String AccountViewPageRoute = "AccountsView";
const String VerificationViewRoute = "VerificationView";
// Generate the views here
